### ISSUE TITLE
For each test suite with a common parameter  QASE_RUN_NAME creates a separate test run.

### ISSUE THREAD

**Issue by JakUi** [qase-tms/qase-robotframework#1]
**Preconditions:**
  All tests suite are run in Gitlab Ci.

**Reproduce**
All tests are run with qase listener. For each test suite, the "qase_run_name" parameter is "test_registration_x". When pipeline finished In the test runs section (https://app.qase.io/run/[project_name]), we get a list of test runs named "test_registration_x", each of them containing one test suite.

An example of a test run file in gitlab ci:

```
Test-suite-1:
  extends:
    - .of
    - .customer-facing-tests-settings
  script: >
    python -m robot.run QASE_API_TOKEN=98f646604b, QASE_RUN_NAME=TestQase_registration_x, QASE_PROJECT=VS, QASE_DEBUG=True
    --listener qaseio.robotframework.Listener Tests/tests_1.robot

Test-suite-2:
  extends:
    - .ofx
    - .customer-facing-tests-settings
  script: >
    python -m robot.run QASE_API_TOKEN=98f646604b, QASE_RUN_NAME=TestQase_registration_x, QASE_PROJECT=VS, QASE_DEBUG=True
    --listener qaseio.robotframework.Listener Tests/tests_2.robot

Test-suite-3:
  extends:
    - .ofx
    - .customer-facing-tests-settings
  script: >
    python -m robot.run QASE_API_TOKEN=98f646604b, QASE_RUN_NAME=TestQase_registration_x, QASE_PROJECT=VS, QASE_DEBUG=True
    --listener qaseio.robotframework.Listener Tests/tests_3.robot
```

 **Example of result:**
![image](https://user-images.githubusercontent.com/48787844/110615526-91764900-81a4-11eb-9bc3-849460d45037.png)

**Expected result:**
After the pipeline ends In the test runs section, we get one test run named "test_registration_x" that contains the entire test suite.
